import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import { connectDB } from "./config/db.js";
import User from "./models/User.js";
import Book from "./models/Book.js";
import Loan from "./models/Loan.js";
import Fine from "./models/Fine.js";
import Alert from "./models/Alert.js";
import ResearchProject from "./models/ResearchProject.js";

dotenv.config();

async function seed() {
  await connectDB();

  await Promise.all([
    User.deleteMany({}),
    Book.deleteMany({}),
    Loan.deleteMany({}),
    Fine.deleteMany({}),
    Alert.deleteMany({}),
    ResearchProject.deleteMany({}),
  ]);

  const passwordHash = await bcrypt.hash("password123", 10);

  const [admin, student, faculty] = await User.create([
    {
      name: "Library Admin",
      email: "admin@uni.edu",
      passwordHash,
      role: "admin",
      department: "Library Operations",
    },
    {
      name: "Aisha Rahman",
      email: "aisha@uni.edu",
      passwordHash,
      role: "student",
      department: "Computer Science",
    },
    {
      name: "Dr Marcus Chen",
      email: "marcus@uni.edu",
      passwordHash,
      role: "faculty",
      department: "Chemistry",
    },
  ]);

  const catalogTemplates = [
    { category: "Computer Science", prefix: "CS", shelf: "CS", topics: ["algorithms", "software engineering", "data structures"], tags: ["cs", "programming"], course: "CS" },
    { category: "Computer Science", prefix: "AI", shelf: "CS", topics: ["artificial intelligence", "machine learning", "neural networks"], tags: ["ai", "ml"], course: "CS" },
    { category: "Mathematics", prefix: "MA", shelf: "MA", topics: ["statistics", "calculus", "linear algebra"], tags: ["math", "quantitative"], course: "MA" },
    { category: "Biology", prefix: "BI", shelf: "BI", topics: ["molecular biology", "genetics", "biochemistry"], tags: ["biology", "life science"], course: "BI" },
    { category: "Economics", prefix: "EC", shelf: "EC", topics: ["microeconomics", "macroeconomics", "policy"], tags: ["economics", "markets"], course: "EC" },
    { category: "Psychology", prefix: "PS", shelf: "PS", topics: ["mental health", "cognitive science", "social behavior"], tags: ["psychology", "wellbeing"], course: "PS" },
    { category: "Information Science", prefix: "IS", shelf: "IS", topics: ["information retrieval", "semantic search", "digital libraries"], tags: ["library science", "search"], course: "IS" },
    { category: "Health Sciences", prefix: "HS", shelf: "HS", topics: ["public health", "epidemiology", "community health"], tags: ["health", "research"], course: "HS" },
    { category: "Education", prefix: "ED", shelf: "ED", topics: ["research methods", "curriculum design", "learning analytics"], tags: ["education", "pedagogy"], course: "ED" },
    { category: "History", prefix: "HI", shelf: "HI", topics: ["world history", "social change", "historical methods"], tags: ["history", "humanities"], course: "HI" },
    { category: "Philosophy", prefix: "PH", shelf: "PH", topics: ["ethics", "logic", "epistemology"], tags: ["philosophy", "critical thinking"], course: "PH" },
    { category: "Chemistry", prefix: "CH", shelf: "CH", topics: ["organic chemistry", "analytical chemistry", "physical chemistry"], tags: ["chemistry", "lab"], course: "CH" },
    { category: "Literature", prefix: "LT", shelf: "LT", topics: ["story books", "fiction", "novels"], tags: ["literature", "stories"], course: "LT" },
  ];

  const authors = [
    "Nina Nguyen", "Arjun Patel", "Elena Garcia", "Rohan Kumar", "Maya Smith", "Aamir Rahman", "Sofia Williams", "Victor Li", "Noah Johnson", "Isabella Brown",
  ];

  const titleBasesByCategory = {
    "Computer Science": [
      "Software Architecture Essentials",
      "Practical Data Structures",
      "Algorithms for Real Systems",
      "Modern Operating Systems Practice",
      "Distributed Systems Design",
      "Programming Language Concepts",
    ],
    Mathematics: [
      "Applied Linear Algebra",
      "Probability for Data Analysis",
      "Foundations of Calculus",
      "Discrete Mathematics Handbook",
      "Numerical Methods in Practice",
      "Statistical Reasoning",
    ],
    Biology: [
      "Cell Biology in Context",
      "Genetics and Genomics",
      "Molecular Biology Toolkit",
      "Principles of Physiology",
      "Evolutionary Biology Today",
      "Laboratory Biology Methods",
    ],
    Economics: [
      "Microeconomic Analysis",
      "Macroeconomic Dynamics",
      "Public Policy Economics",
      "Behavioral Economic Insights",
      "Econometrics Fundamentals",
      "Global Market Structures",
    ],
    Psychology: [
      "Cognitive Psychology Foundations",
      "Mental Health and Society",
      "Social Behavior Perspectives",
      "Psychology Research Methods",
      "Emotion and Decision Making",
      "Wellbeing Studies",
    ],
    "Information Science": [
      "Information Retrieval Systems",
      "Digital Libraries Design",
      "Semantic Knowledge Organization",
      "Metadata and Discovery",
      "User Search Behavior",
      "Research Data Curation",
    ],
    "Health Sciences": [
      "Community Health Analytics",
      "Public Health Practice",
      "Epidemiology and Evidence",
      "Healthcare Policy Studies",
      "Preventive Medicine Basics",
      "Global Health Challenges",
    ],
    Education: [
      "Learning Theory and Practice",
      "Curriculum Design Strategies",
      "Assessment and Evaluation",
      "Educational Research Methods",
      "Instructional Design Principles",
      "Classroom Analytics",
    ],
    History: [
      "World History Perspectives",
      "Modern Social Transformations",
      "Historical Methods and Sources",
      "Comparative Civilizations",
      "Global Conflicts and Change",
      "Cultural History Studies",
    ],
    Philosophy: [
      "Ethics in Contemporary Society",
      "Logic and Critical Reasoning",
      "Philosophy of Technology",
      "Epistemology Explained",
      "Moral Decision Frameworks",
      "Political Philosophy Debates",
    ],
    Chemistry: [
      "Organic Chemistry in Practice",
      "Analytical Chemistry Methods",
      "Physical Chemistry Concepts",
      "Chemical Kinetics Essentials",
      "Laboratory Safety and Design",
      "Spectroscopy Applications",
    ],
    Literature: [
      "World Story Collections",
      "Modern Fiction Essentials",
      "Short Stories and Narrative Craft",
      "Classic Novels Revisited",
      "Contemporary Literary Themes",
      "Storytelling Across Cultures",
    ],
  };

  const subtitlePool = [
    "Theory and Practice",
    "Methods and Applications",
    "An Interdisciplinary Approach",
    "Contemporary Perspectives",
    "Case Studies Edition",
    "for University Learners",
  ];

  const generatedBooks = Array.from({ length: 110 }, (_, index) => {
    const template = catalogTemplates[index % catalogTemplates.length];
    const cohort = Math.floor(index / catalogTemplates.length);
    const number = index + 19;
    const code = `B${String(number).padStart(3, "0")}`;
    const titleBase = titleBasesByCategory[template.category][cohort % titleBasesByCategory[template.category].length];
    const subtitle = subtitlePool[(cohort + 2) % subtitlePool.length];
    const title = `${titleBase}: ${subtitle}`;
    const author = authors[index % authors.length];
    const totalCopies = 3 + (index % 8);
    const stock = index % 11 === 0 ? 0 : Math.min(totalCopies, 1 + (index % totalCopies));
    const demandScore = 45 + ((index * 7) % 55);
    const examSeasonImpact = demandScore > 85 ? "Very High" : demandScore > 72 ? "High" : demandScore > 58 ? "Medium" : "Low";
    const floor = (index % 3) + 1;
    const shelf = `${template.shelf}-${String((index % 18) + 1).padStart(2, "0")}`;
    const row = (index % 4) + 1;

    return {
      code,
      title,
      author,
      category: template.category,
      isbn: `978-${String(1000000000 + number).padStart(10, "0")}`,
      stock,
      totalCopies,
      location: { floor, shelf, row },
      examSeasonImpact,
      demandScore,
      semanticTopics: [...template.topics, "research"],
      tags: [...template.tags, template.prefix.toLowerCase()],
      courseCodes: [`${template.course}${200 + (index % 260)}`],
    };
  });

  const urbanPovertyBooks = [
    {
      code: "UP001",
      title: "Urban Poverty and Social Policy",
      author: "R. Delgado",
      category: "Economics",
      isbn: "978-1000002001",
      stock: 4,
      totalCopies: 6,
      location: { floor: 3, shelf: "EC-19", row: 1 },
      examSeasonImpact: "High",
      demandScore: 86,
      semanticTopics: ["urban poverty", "social policy", "income inequality", "development economics"],
      tags: ["economics", "urban inequality", "policy"],
      courseCodes: ["EC420"],
    },
    {
      code: "UP002",
      title: "Inequality in Growing Cities",
      author: "M. Torres",
      category: "Economics",
      isbn: "978-1000002002",
      stock: 3,
      totalCopies: 5,
      location: { floor: 3, shelf: "EC-20", row: 2 },
      examSeasonImpact: "Medium",
      demandScore: 81,
      semanticTopics: ["urban inequality", "poverty", "housing inequality", "labor markets"],
      tags: ["urban poverty", "economics", "cities"],
      courseCodes: ["EC421"],
    },
    {
      code: "UP003",
      title: "Development Economics for Urban Communities",
      author: "S. Ibrahim",
      category: "Economics",
      isbn: "978-1000002003",
      stock: 5,
      totalCopies: 7,
      location: { floor: 3, shelf: "EC-21", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 79,
      semanticTopics: ["development economics", "urban poverty", "community development"],
      tags: ["poverty", "development", "policy"],
      courseCodes: ["EC422"],
    },
    {
      code: "UP004",
      title: "Public Policy for Informal Settlements",
      author: "A. Mukherjee",
      category: "Economics",
      isbn: "978-1000002004",
      stock: 2,
      totalCopies: 4,
      location: { floor: 3, shelf: "EC-22", row: 2 },
      examSeasonImpact: "High",
      demandScore: 84,
      semanticTopics: ["urban poverty", "public policy", "housing", "inequality"],
      tags: ["slums", "urban policy", "economics"],
      courseCodes: ["EC423"],
    },
    {
      code: "UP005",
      title: "Research Methods in Poverty Studies",
      author: "K. Bennett",
      category: "Education",
      isbn: "978-1000002005",
      stock: 4,
      totalCopies: 5,
      location: { floor: 3, shelf: "ED-14", row: 2 },
      examSeasonImpact: "Medium",
      demandScore: 72,
      semanticTopics: ["poverty research", "research methods", "peer reviewed studies"],
      tags: ["methodology", "urban poverty", "evidence"],
      courseCodes: ["ED430"],
    },
    {
      code: "UP006",
      title: "Community Health in Low-Income Neighborhoods",
      author: "L. Fernandes",
      category: "Health Sciences",
      isbn: "978-1000002006",
      stock: 3,
      totalCopies: 5,
      location: { floor: 1, shelf: "HS-17", row: 3 },
      examSeasonImpact: "Medium",
      demandScore: 75,
      semanticTopics: ["urban poverty", "community health", "social determinants"],
      tags: ["public health", "inequality", "urban"],
      courseCodes: ["HS330"],
    },
    {
      code: "UP007",
      title: "Housing, Work, and Urban Exclusion",
      author: "P. Osei",
      category: "History",
      isbn: "978-1000002007",
      stock: 2,
      totalCopies: 4,
      location: { floor: 3, shelf: "HI-14", row: 1 },
      examSeasonImpact: "Low",
      demandScore: 68,
      semanticTopics: ["urban poverty", "social change", "housing inequality"],
      tags: ["urban inequality", "history", "policy"],
      courseCodes: ["HI350"],
    },
    {
      code: "UP008",
      title: "Data Analysis for Urban Poverty Research",
      author: "V. Shah",
      category: "Mathematics",
      isbn: "978-1000002008",
      stock: 3,
      totalCopies: 5,
      location: { floor: 2, shelf: "MA-18", row: 2 },
      examSeasonImpact: "High",
      demandScore: 80,
      semanticTopics: ["urban poverty", "statistics", "quantitative methods"],
      tags: ["data analysis", "peer reviewed", "inequality"],
      courseCodes: ["ST410"],
    },
  ];

  const books = await Book.create([
    {
      code: "B001",
      title: "Introduction to Algorithms",
      author: "Cormen, Leiserson",
      category: "Computer Science",
      isbn: "978-0262033848",
      stock: 5,
      totalCopies: 8,
      location: { floor: 2, shelf: "CS-12", row: 3 },
      examSeasonImpact: "High",
      demandScore: 92,
      semanticTopics: ["machine learning", "algorithms", "data structures"],
      tags: ["cs", "theory"],
      courseCodes: ["CS201", "CS301"],
    },
    {
      code: "B002",
      title: "Organic Chemistry",
      author: "Clayden, Greeves",
      category: "Chemistry",
      isbn: "978-0199270293",
      stock: 2,
      totalCopies: 6,
      location: { floor: 1, shelf: "CH-05", row: 1 },
      examSeasonImpact: "Very High",
      demandScore: 88,
      semanticTopics: ["biochemistry", "organic synthesis", "molecular structure"],
      tags: ["chemistry"],
      courseCodes: ["CH101"],
    },
    {
      code: "B003",
      title: "Principles of Economics",
      author: "Mankiw",
      category: "Economics",
      isbn: "978-1305585126",
      stock: 0,
      totalCopies: 4,
      location: { floor: 3, shelf: "EC-01", row: 2 },
      examSeasonImpact: "High",
      demandScore: 84,
      semanticTopics: ["microeconomics", "markets", "policy"],
      tags: ["economics"],
      courseCodes: ["EC200"],
    },
    {
      code: "B004",
      title: "Deep Learning",
      author: "Goodfellow, Bengio, Courville",
      category: "Computer Science",
      isbn: "978-0262035613",
      stock: 1,
      totalCopies: 3,
      location: { floor: 2, shelf: "CS-14", row: 1 },
      examSeasonImpact: "Very High",
      demandScore: 96,
      semanticTopics: ["machine learning", "artificial intelligence", "neural networks"],
      tags: ["ai", "ml", "data science"],
      courseCodes: ["CS410"],
    },
    {
      code: "B005",
      title: "Linear Algebra Done Right",
      author: "Axler",
      category: "Mathematics",
      isbn: "978-3319110790",
      stock: 7,
      totalCopies: 10,
      location: { floor: 2, shelf: "MA-03", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 62,
      semanticTopics: ["linear algebra", "vector spaces", "mathematics"],
      tags: ["math", "algebra"],
      courseCodes: ["MA201"],
    },
    {
      code: "B006",
      title: "Campbell Biology",
      author: "Urry, Cain",
      category: "Biology",
      isbn: "978-0134093413",
      stock: 6,
      totalCopies: 8,
      location: { floor: 1, shelf: "BI-02", row: 3 },
      examSeasonImpact: "Medium",
      demandScore: 68,
      semanticTopics: ["molecular biology", "genetics", "biochemistry"],
      tags: ["biology", "life science"],
      courseCodes: ["BI101"],
    },
    {
      code: "B007",
      title: "Human Anatomy and Physiology",
      author: "Marieb, Hoehn",
      category: "Biology",
      isbn: "978-0134243818",
      stock: 3,
      totalCopies: 5,
      location: { floor: 1, shelf: "BI-08", row: 4 },
      examSeasonImpact: "High",
      demandScore: 74,
      semanticTopics: ["anatomy", "physiology", "health sciences"],
      tags: ["medicine", "biology"],
      courseCodes: ["BI220"],
    },
    {
      code: "B008",
      title: "Database System Concepts",
      author: "Silberschatz, Korth",
      category: "Computer Science",
      isbn: "978-0078022159",
      stock: 4,
      totalCopies: 6,
      location: { floor: 2, shelf: "CS-07", row: 2 },
      examSeasonImpact: "High",
      demandScore: 79,
      semanticTopics: ["databases", "sql", "data management"],
      tags: ["dbms", "computer science"],
      courseCodes: ["CS304"],
    },
    {
      code: "B009",
      title: "Computer Networks",
      author: "Tanenbaum, Wetherall",
      category: "Computer Science",
      isbn: "978-0132126953",
      stock: 5,
      totalCopies: 7,
      location: { floor: 2, shelf: "CS-09", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 71,
      semanticTopics: ["computer networks", "network security", "internet protocols"],
      tags: ["networking", "cybersecurity"],
      courseCodes: ["CS330"],
    },
    {
      code: "B010",
      title: "Cybersecurity Essentials",
      author: "Simmons",
      category: "Computer Science",
      isbn: "978-1305075979",
      stock: 4,
      totalCopies: 5,
      location: { floor: 2, shelf: "CS-15", row: 2 },
      examSeasonImpact: "High",
      demandScore: 83,
      semanticTopics: ["cybersecurity", "information security", "cryptography"],
      tags: ["security", "cyber defense"],
      courseCodes: ["CS350"],
    },
    {
      code: "B011",
      title: "Statistical Inference",
      author: "Casella, Berger",
      category: "Mathematics",
      isbn: "978-0534243128",
      stock: 2,
      totalCopies: 4,
      location: { floor: 2, shelf: "MA-06", row: 2 },
      examSeasonImpact: "High",
      demandScore: 82,
      semanticTopics: ["statistics", "probability", "inference"],
      tags: ["data analysis", "quantitative methods"],
      courseCodes: ["ST301"],
    },
    {
      code: "B012",
      title: "Behavioral Economics",
      author: "Kahneman",
      category: "Economics",
      isbn: "978-0141033570",
      stock: 3,
      totalCopies: 5,
      location: { floor: 3, shelf: "EC-04", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 69,
      semanticTopics: ["microeconomics", "behavioral economics", "decision making"],
      tags: ["economics", "policy"],
      courseCodes: ["EC310"],
    },
    {
      code: "B013",
      title: "Social Psychology",
      author: "Aronson, Wilson",
      category: "Psychology",
      isbn: "978-0133936544",
      stock: 5,
      totalCopies: 6,
      location: { floor: 3, shelf: "PS-02", row: 3 },
      examSeasonImpact: "Medium",
      demandScore: 64,
      semanticTopics: ["mental health", "social behavior", "wellbeing"],
      tags: ["psychology", "social isolation", "loneliness"],
      courseCodes: ["PS210"],
    },
    {
      code: "B014",
      title: "Public Health and Epidemiology",
      author: "Schneider",
      category: "Health Sciences",
      isbn: "978-1284023011",
      stock: 2,
      totalCopies: 4,
      location: { floor: 1, shelf: "HS-03", row: 2 },
      examSeasonImpact: "High",
      demandScore: 76,
      semanticTopics: ["public health", "epidemiology", "mental health"],
      tags: ["health", "community"],
      courseCodes: ["HS205"],
    },
    {
      code: "B015",
      title: "Research Methods in Education",
      author: "Cohen, Manion",
      category: "Education",
      isbn: "978-0415583367",
      stock: 4,
      totalCopies: 5,
      location: { floor: 3, shelf: "ED-01", row: 2 },
      examSeasonImpact: "Low",
      demandScore: 57,
      semanticTopics: ["research methods", "qualitative", "quantitative"],
      tags: ["research", "methodology"],
      courseCodes: ["ED401"],
    },
    {
      code: "B016",
      title: "Digital Libraries and Information Retrieval",
      author: "Baeza-Yates",
      category: "Information Science",
      isbn: "978-0321416919",
      stock: 3,
      totalCopies: 5,
      location: { floor: 3, shelf: "IS-05", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 73,
      semanticTopics: ["information retrieval", "semantic search", "digital libraries"],
      tags: ["library science", "search systems"],
      courseCodes: ["IS320"],
    },
    {
      code: "B017",
      title: "Cloud Computing Concepts",
      author: "Erl",
      category: "Computer Science",
      isbn: "978-0133387520",
      stock: 6,
      totalCopies: 7,
      location: { floor: 2, shelf: "CS-18", row: 1 },
      examSeasonImpact: "Medium",
      demandScore: 66,
      semanticTopics: ["cloud computing", "distributed systems", "devops"],
      tags: ["systems", "infrastructure"],
      courseCodes: ["CS430"],
    },
    {
      code: "B018",
      title: "Ethics in Artificial Intelligence",
      author: "Coeckelbergh",
      category: "Philosophy",
      isbn: "978-0262538190",
      stock: 2,
      totalCopies: 3,
      location: { floor: 3, shelf: "PH-04", row: 2 },
      examSeasonImpact: "Medium",
      demandScore: 70,
      semanticTopics: ["artificial intelligence", "ethics", "policy"],
      tags: ["ai", "responsible technology"],
      courseCodes: ["PH315"],
    },
    ...urbanPovertyBooks,
    ...generatedBooks,
  ]);

  const activeLoan = await Loan.create({
    user: student._id,
    book: books[0]._id,
    borrowDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3),
    borrowPolicyDays: 7,
  });

  await Fine.create({
    user: faculty._id,
    loan: activeLoan._id,
    amount: 15,
    reason: "Legacy overdue balance",
    status: "pending",
  });

  await Alert.create([
    { type: "due", message: "Reminder: Introduction to Algorithms due in 3 days", recipient: student._id },
    { type: "stock", message: "Principles of Economics has high reservation demand", recipient: null },
  ]);

  await ResearchProject.create({
    user: student._id,
    topic: "Impact of AI on Academic Libraries",
    researchQuestion: "How is AI changing library discovery, circulation, and research support in universities?",
    methodology: "Comparative literature review with service design analysis",
    status: "reading",
    keywords: ["academic libraries", "artificial intelligence", "discovery systems", "student research"],
    notes: "Focus on practical workflow changes rather than speculative automation claims.",
    targetCompletionDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12),
    sourceBooks: [
      { book: books[0]._id, status: "reading" },
      { book: books[1]._id, status: "saved" },
      { book: books[2]._id, status: "cited" },
    ],
    tasks: [
      { title: "Finalize the scope of the research question", status: "done", notes: "Question approved by supervisor" },
      { title: "Review and annotate core library systems sources", status: "in_progress", notes: "8 annotations completed" },
      { title: "Draft findings section on circulation workflows", status: "todo", notes: "" },
    ],
  });

  console.log("Seed complete");
  console.log("Admin login: admin@uni.edu / password123");
  console.log("Student login: aisha@uni.edu / password123");
  process.exit(0);
}

seed().catch((error) => {
  console.error(error);
  process.exit(1);
});
